- hosts: all
  become: yes
  tasks: 

    - name: Remove Nginx
      dnf: 
        name: nginx
        state: absent
        update_cache: yes

    - name: Remove pip
      dnf: 
        name: python3-pip
        state: absent
        update_cache: yes
        