---

- hosts: all
  become: yes
  pre_tasks:

    - name: Install Updates
      dnf: 
        name: '*'
        state: latest
        update_cache: yes
      

- hosts: webservers
  become: yes
  tasks:

    - name: Remove Nginx
      dnf: 
        name: nginx
        state: absent
        update_cache: yes

- hosts: wsgi
  become: yes
  tasks:

    - name: Install Python3
      dnf: 
        name: python3
        state: latest
        update_cache: yes

    - name: Uninstall Gunicorn
      pip:
        name: gunicorn
        state: absent

    - name: Uninstall Python3-pip
      dnf: 
        name: python3-pip
        state: absent
        update_cache: yes
        

- hosts: flask 
  become: yes
  tasks:

    - name: Install Python3
      dnf: 
        name: python3
        state: latest
        update_cache: yes

    - name: Uninstall Flask
      pip:
        name: flask
        state: absent 

    - name: Uninstall Python3-pip
      dnf: 
        name: python3-pip
        state: absent
        update_cache: yes

